resources:
  - name: super-app
    type: git
    branch: ci
    source:
      uri: https://github.com/fernandagallina/concourse-tutorial.git

jobs:
  - name: Testing
    plan:
    - get: super-app
      trigger: true
    - aggregate:
      - task: lint
        file: super-app/tasks/lint.yml

      - task: unit
        file: super-app/tasks/unit.yml

  - name: Building
    plan:
    - get: super-app
      passed: ["Testing"]
      trigger: true

    - task: build
      file: super-app/tasks/build.yml

    - task: integration test
      file: super-app/tasks/integration.yml
