resources:
  - name: super-app
    type: git
    source:
      uri: https://github.com/fernandagallina/concourse-tutorial.git
      branch: ci

jobs:
  - name: initial testing
    plan:
    - get: super-app
      trigger: true

    - aggregate:
      - task: run unit
        file: super-app/tasks/unit.yml

      - task: run lint
        file: super-app/tasks/lint.yml


  - name: Master build
    plan:
    - get: super-app
      passed: ["initial testing"]
      trigger: true
    - aggregate:
      - task: build linux
        file: super-app/tasks/build_linux.yml

      - task: build darwin
        file: super-app/tasks/build_darwin.yml

      - task: build windows
        file: super-app/tasks/build_windows.yml


    # - task: integeration test
    #   file: super-app/tutorial/scenario.4/1-multi-os/tasks/integeration.yml
